name: Publish 🚀

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '11.0.x'

      - name: Restore
        run: dotnet restore $(find . -name "*.sln" -print -quit)

      - name: Build
        run: dotnet build $(find . -name "*.sln" -print -quit) --configuration Release --no-restore

      - name: Publish
        run: dotnet publish $(find . -name "*.sln" -print -quit) --configuration Release --no-build --output ./publish

      - name: Deployment
        uses: azure/webapps-deploy@v3
        with:
           app-name: 'time-service'
           publish-profile: ${{ secrets.AZUR_PUBLISH_PROFILE }}
           package: ./publish
